### ISSUE TITLE
Example lit-element-ts-tsc is broken, due to @web/parse5-utils being broken with Node < 12.17

### ISSUE THREAD

**Issue by ChristianUlbrich** [modernweb-dev/example-projects#191]
Problem is some olde Node -> < 12.17 .
# Repro
* clone repo
* `cd lit-element-ts-tsc`
* `npm i`
* `npm run start:watch`
* **BOOM**

> Error: Cannot find module '{redacted}/web-dev-server-examples/lit-element-ts-tsc/node_modules/@web/parse5-utils/dist/index.js'. Please verify that the package.json has a valid "main" entry

Quick-Hack is _modifying_ its `package.json` to point to `src/index.js`. Should be fixed, with new version of `@web/dev-server`.

-> https://github.com/modernweb-dev/web/issues/870

**Comment by LarsDenBakker** [comment]
Looks to be fixd with the latest dev-server
