### ISSUE TITLE
Can we add React in example-projects?

### ISSUE THREAD

**Issue by rajasegar** [modernweb-dev/example-projects#198]
It would be great if we can add React apps here, something like
- react-jsx
- react-htm
- react-tsx

I tried to build react with htm, seems like the npm package is not ESM compatible, but we can use something like [esm-react](https://www.npmjs.com/package/esm-react) I guess. There are also a lot of alternatives:
- [snowpackjs/react](https://github.com/snowpackjs/react)
- [@esm-bundle/react](https://github.com/esm-bundle/react)

**Comment by LarsDenBakker** [comment]
We can add it, but indeed the packaging is a challenge. Let's try the esm-bundle since we use that in other places too.

**Comment by rajasegar** [comment]
esm-bundle/react is not working , the browser hangs while trying to load the app
https://github.com/esm-bundle/react/issues/90
