### ISSUE TITLE
LitELement error on Tests

### ISSUE THREAD

**Issue by imtiyazthange** [modernweb-dev/example-projects#83]
Not able to run tests on LitElements Pexample projects.

> @web/demo-lit-element@0.1.0 test D:\Work\Test Project\example-projects-master\lit-element
> web-test-runner test/**/*.test.js --coverage --node-resolve

  Error: Could not find a test framework at D:\Work\Test%20Project\example-projects-master\lit-element\node_modules\@web\test-runner-mocha\dist\autorun.js
      at readFile (D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\test-runner-core\dist\server\plugins\serveTestFrameworkPlugin.js:14:15)
      at Object.serve (D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\test-runner-core\dist\server\plugins\serveTestFrameworkPlugin.js:35:36)
      at D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\dev-server-core\dist\middleware\pluginServeMiddleware.js:20:97
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\dev-server-core\dist\middleware\pluginTransformMiddleware.js:36:9
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\dev-server-core\dist\middleware\etagCacheMiddleware.js:9:9
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\dev-server-core\dist\middleware\watchServedFilesMiddleware.js:15:9
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\test-runner-core\dist\server\middleware\cacheMiddleware.js:10:9
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\test-runner-core\dist\server\middleware\watchFilesMiddleware.js:148:9
      at async D:\Work\Test Project\example-projects-master\lit-element\node_modules\@web\dev-server-core\dist\server\createMiddleware.js:26:9

test\my-element.test.js:

**Comment by LarsDenBakker** [comment]
@imtiyazthange That's odd, does the path ` D:\Work\Test%20Project\example-projects-master\lit-element\node_modules@web\test-runner-mocha\dist\autorun.js` make any sense? 

What do you see inside ` D:\Work\Test%20Project\example-projects-master\lit-element\node_modules@web` ?

**Comment by imtiyazthange** [comment]
Yeah the path ` D:\Work\Test%20Project\example-projects-master\lit-element\node_modules@web\test-runner-mocha\dist\autorun.js` is invalid path, it should be ` D:\Work\Test%20Project\example-projects-master\lit-element\node_modules\@web\test-runner-mocha\dist\autorun.js` .

I did run `npm install` before running the test.

Just an FYI, I am able to successfully run npm start command, the error is in `npm run test` command only

**Comment by LarsDenBakker** [comment]
The strange thing is that all the paths in your stack trace are like this 🤔 

We just do a `require.resolve`: https://github.com/modernweb-dev/web/blob/master/packages/test-runner/src/startTestRunner.ts#L119

Would you be able to run this in the node REPL (with the command `node`):

```
console.log(require.resolve('@web/test-runner-mocha/dist/autorun.js'))
```

**Comment by imtiyazthange** [comment]
As mentioned in the previous comment this issue is fixed by removing the space from the parent folder name, may be valid bug, but nothing to worry about it right now.

Something else I am struggling right now.

In my case I need to verify the snapshot of the shadowroot, so I am writing below test statement and it is throwing error.

`await expect(el).shadowDom.to.be.equalSnapshot();`


I am getting below error.

 at: node_modules\@open-wc\semantic-dom-diff\chai-dom-diff.js:122:13
      TypeError: Cannot destructure property 'index' of 'context' as it is undefined.
        at Proxy.assertHtmlEqualsSnapshot (node_modules\@open-wc\semantic-dom-diff\chai-dom-diff.js:122:13)
        at Proxy.equalSnapshot (node_modules\@open-wc\semantic-dom-diff\chai-dom-diff.js:173:37)
        at Proxy.methodWrapper (node_modules\chai\chai.js:7824:25)
        at n.<anonymous> `(test\my-element.test.js:37:38)`

**Comment by LarsDenBakker** [comment]
We don't support the snapshot testing from `chai-dom-diff` yet :)

**Comment by imtiyazthange** [comment]
Thanks for very quick response. 
any other alternative you would recommend to overcome this one.

**Comment by LarsDenBakker** [comment]
Personally I prefer checking is certain elements are there using querySelector, a snapshot test can easily get a bit messy.

You can import `getDiffableHtml` yourself and do a string equals on that: https://github.com/open-wc/open-wc/blob/master/packages/semantic-dom-diff/index.js#L1

**Comment by filipbech** [comment]
I encountered the same issue today, and the fix/workaround of "removing the whitespace in the root-folder name" also worked here... I dont understand it though...!
